
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace PalCalc.UI.Localization {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationCodesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationCodesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalCalc.UI.Localization.LocalizationCodes", typeof(LocalizationCodesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }

    /// <summary>
    /// Keys of all available strings in the applications resx-resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public enum LocalizationCodes
    {
        /// <summary>
        ///   Looks up a localized string similar to LC_ABOUT_APP.
        /// </summary>
        LC_ABOUT_APP,
        /// <summary>
        ///   Looks up a localized string similar to LC_ADD_NEW_SAVE.
        /// </summary>
        LC_ADD_NEW_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to LC_ANY_GUILD.
        /// </summary>
        LC_ANY_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to LC_ANY_PLAYER.
        /// </summary>
        LC_ANY_PLAYER,
        /// <summary>
        ///   Looks up a localized string similar to LC_BASE_LABEL | BaseName.
        /// </summary>
        LC_BASE_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_BREEDING_TIMES.
        /// </summary>
        LC_BREEDING_TIME,
        /// <summary>
        ///   Looks up a localized string similar to LC_BREEDING_TIME_DESC.
        /// </summary>
        LC_BREEDING_TIME_DESC,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_CANCEL.
        /// </summary>
        LC_COMMON_CANCEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_ENABLED.
        /// </summary>
        LC_COMMON_ENABLED,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_GENDER.
        /// </summary>
        LC_COMMON_GENDER,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_GENDER_FEMALE.
        /// </summary>
        LC_COMMON_GENDER_FEMALE,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_GENDER_MALE.
        /// </summary>
        LC_COMMON_GENDER_MALE,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_GENDER_OPPOSITE_WILDCARD.
        /// </summary>
        LC_COMMON_GENDER_OPPOSITE_WILDCARD,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_GENDER_WILDCARD.
        /// </summary>
        LC_COMMON_GENDER_WILDCARD,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_IV_ATTACK.
        /// </summary>
        LC_COMMON_IV_ATTACK,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_IV_DEFENSE.
        /// </summary>
        LC_COMMON_IV_DEFENSE,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_IV_HP.
        /// </summary>
        LC_COMMON_IV_HP,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_IVS.
        /// </summary>
        LC_COMMON_IVS,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_LEVEL.
        /// </summary>
        LC_COMMON_LEVEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_PAL.
        /// </summary>
        LC_COMMON_PAL,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_PALDEX_NUM_SHORT.
        /// </summary>
        LC_COMMON_PALDEX_NUM_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_SAVE.
        /// </summary>
        LC_COMMON_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_TRAITS.
        /// </summary>
        LC_COMMON_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_COMMON_UNKNOWN.
        /// </summary>
        LC_COMMON_UNKNOWN,
        /// <summary>
        ///   Looks up a localized string similar to LC_CRASHLOG_FAILED.
        /// </summary>
        LC_CRASHLOG_FAILED,
        /// <summary>
        ///   Looks up a localized string similar to LC_DELETE_PAL_TARGET_MSG | PalName.
        /// </summary>
        LC_DELETE_PAL_TARGET_MSG,
        /// <summary>
        ///   Looks up a localized string similar to LC_DELETE_PAL_TARGET_TITLE.
        /// </summary>
        LC_DELETE_PAL_TARGET_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to LC_ERROR_HARD_CRASH | CrashlogPath.
        /// </summary>
        LC_ERROR_HARD_CRASH,
        /// <summary>
        ///   Looks up a localized string similar to LC_ERROR_SAVE_LOAD_FAILED | CrashlogPath.
        /// </summary>
        LC_ERROR_SAVE_LOAD_FAILED,
        /// <summary>
        ///   Looks up a localized string similar to LC_EXPORT_CRASH_LOG.
        /// </summary>
        LC_EXPORT_CRASH_LOG,
        /// <summary>
        ///   Looks up a localized string similar to LC_EXPORT_CRASH_LOG_DESCRIPTION.
        /// </summary>
        LC_EXPORT_CRASH_LOG_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_EXPORT_SAVE.
        /// </summary>
        LC_EXPORT_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to LC_EXPORT_SAVE_DESCRIPTION.
        /// </summary>
        LC_EXPORT_SAVE_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_GAME_SETTINGS.
        /// </summary>
        LC_GAME_SETTINGS,
        /// <summary>
        ///   Looks up a localized string similar to LC_GRAPH_ZOOM_CUSTOM.
        /// </summary>
        LC_GRAPH_ZOOM_CUSTOM,
        /// <summary>
        ///   Looks up a localized string similar to LC_GRAPH_ZOOM_FILL.
        /// </summary>
        LC_GRAPH_ZOOM_FILL,
        /// <summary>
        ///   Looks up a localized string similar to LC_GRAPH_ZOOM_PERCENT.
        /// </summary>
        LC_GRAPH_ZOOM_PERCENT,
        /// <summary>
        ///   Looks up a localized string similar to LC_GUILD_LABEL | GuildName.
        /// </summary>
        LC_GUILD_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_INSPECT_SAVE.
        /// </summary>
        LC_INSPECT_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to LC_ITL_LABEL.
        /// </summary>
        /// <remarks>
        /// Label used to represent this language in the dropdown
        /// </remarks>
        LC_ITL_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_LANG_CHANGED_RESTART.
        /// </summary>
        LC_LANG_CHANGED_RESTART,
        /// <summary>
        ///   Looks up a localized string similar to LC_LANGUAGE.
        /// </summary>
        LC_LANGUAGE,
        /// <summary>
        ///   Looks up a localized string similar to LC_LIST_SEPARATOR.
        /// </summary>
        LC_LIST_SEPARATOR,
        /// <summary>
        ///   Looks up a localized string similar to LC_LOC_COORD_BASE | X | Y.
        /// </summary>
        LC_LOC_COORD_BASE,
        /// <summary>
        ///   Looks up a localized string similar to LC_LOC_COORD_PALBOX | Tab | X | Y.
        /// </summary>
        LC_LOC_COORD_PALBOX,
        /// <summary>
        ///   Looks up a localized string similar to LC_LOC_COORD_PARTY | SlotNum.
        /// </summary>
        LC_LOC_COORD_PARTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_LOC_OWNED_BY | Owner.
        /// </summary>
        LC_LOC_OWNED_BY,
        /// <summary>
        ///   Looks up a localized string similar to LC_LOC_PALBOX_TAB | Tab.
        /// </summary>
        LC_LOC_PALBOX_TAB,
        /// <summary>
        ///   Looks up a localized string similar to LC_MANUAL_SAVE_ALREADY_REGISTERED.
        /// </summary>
        LC_MANUAL_SAVE_ALREADY_REGISTERED,
        /// <summary>
        ///   Looks up a localized string similar to LC_MANUAL_SAVE_EXTENSION_LBL.
        /// </summary>
        LC_MANUAL_SAVE_EXTENSION_LBL,
        /// <summary>
        ///   Looks up a localized string similar to LC_MANUAL_SAVE_INCOMPLETE.
        /// </summary>
        LC_MANUAL_SAVE_INCOMPLETE,
        /// <summary>
        ///   Looks up a localized string similar to LC_MANUAL_SAVE_SELECTOR_TITLE.
        /// </summary>
        LC_MANUAL_SAVE_SELECTOR_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to LC_MULTIPLE_BREEDING_FARMS.
        /// </summary>
        LC_MULTIPLE_BREEDING_FARMS,
        /// <summary>
        ///   Looks up a localized string similar to LC_MULTIPLE_BREEDING_FARMS_DESC.
        /// </summary>
        LC_MULTIPLE_BREEDING_FARMS_DESC,
        /// <summary>
        ///   Looks up a localized string similar to LC_NEW_TARGET_PAL.
        /// </summary>
        LC_NEW_TARGET_PAL,
        /// <summary>
        ///   Looks up a localized string similar to LC_NO_TRAITS.
        /// </summary>
        LC_NO_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_OPEN_IN_FILE_EXPLORER.
        /// </summary>
        LC_OPEN_IN_FILE_EXPLORER,
        /// <summary>
        ///   Looks up a localized string similar to LC_OPTIONAL_TRAITS_SUMMARY | TraitsList.
        /// </summary>
        LC_OPTIONAL_TRAITS_SUMMARY,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_CHECKLIST_SEARCH.
        /// </summary>
        LC_PAL_CHECKLIST_SEARCH,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LABEL | PalName | PaldexNum.
        /// </summary>
        LC_PAL_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LOC_BASE.
        /// </summary>
        LC_PAL_LOC_BASE,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LOC_CAPTURED.
        /// </summary>
        LC_PAL_LOC_CAPTURED,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LOC_COUNT | Count | LocType.
        /// </summary>
        LC_PAL_LOC_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LOC_PALBOX.
        /// </summary>
        LC_PAL_LOC_PALBOX,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_LOC_PARTY.
        /// </summary>
        LC_PAL_LOC_PARTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_SRC_ANY_GUILD_MEMBER.
        /// </summary>
        LC_PAL_SRC_ANY_GUILD_MEMBER,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_SRC_ANY_PLAYER_GUILD.
        /// </summary>
        LC_PAL_SRC_ANY_PLAYER_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_TARGET_OPTIONAL_TRAITS.
        /// </summary>
        LC_PAL_TARGET_OPTIONAL_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_TARGET_REQUIRED_TRAITS.
        /// </summary>
        LC_PAL_TARGET_REQUIRED_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_PAL_WILD_COUNT | NumWild.
        /// </summary>
        LC_PAL_WILD_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to LC_PALS_AT_BASE.
        /// </summary>
        LC_PALS_AT_BASE,
        /// <summary>
        ///   Looks up a localized string similar to LC_PLAYER_LABEL | PlayerName.
        /// </summary>
        LC_PLAYER_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_POPUP_TITLE_LOADING_SAVE_FILE.
        /// </summary>
        LC_POPUP_TITLE_LOADING_SAVE_FILE,
        /// <summary>
        ///   Looks up a localized string similar to LC_RANDOM_TRAIT.
        /// </summary>
        LC_RANDOM_TRAIT,
        /// <summary>
        ///   Looks up a localized string similar to LC_REQUIRED_TRAITS_SUMMARY | TraitsList.
        /// </summary>
        LC_REQUIRED_TRAITS_SUMMARY,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_BREEDING_ATTEMPTS | AvgAttempts.
        /// </summary>
        LC_RESULT_BREEDING_ATTEMPTS,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_INPUT_LOCS.
        /// </summary>
        LC_RESULT_INPUT_LOCS,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_LABEL | PalName | TraitsList | TimeEstim....
        /// </summary>
        LC_RESULT_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_LIST_TITLE_COUNT | NumResults.
        /// </summary>
        LC_RESULT_LIST_TITLE_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_LIST_TITLE_EMPTY.
        /// </summary>
        LC_RESULT_LIST_TITLE_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_NUM_STEPS.
        /// </summary>
        LC_RESULT_NUM_STEPS,
        /// <summary>
        ///   Looks up a localized string similar to LC_RESULT_TIME_ESTIMATE.
        /// </summary>
        LC_RESULT_TIME_ESTIMATE,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_FILE.
        /// </summary>
        LC_SAVE_FILE,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_FILE_RELOADING.
        /// </summary>
        LC_SAVE_FILE_RELOADING,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME.
        /// </summary>
        LC_SAVE_GAME,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME_INVALID.
        /// </summary>
        LC_SAVE_GAME_INVALID,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME_LBL | PlayerName | PlayerLevel | DayN....
        /// </summary>
        LC_SAVE_GAME_LBL,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME_LBL_NO_METADATA | GameId.
        /// </summary>
        LC_SAVE_GAME_LBL_NO_METADATA,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME_LBL_SERVER | DayNumber | WorldName.
        /// </summary>
        LC_SAVE_GAME_LBL_SERVER,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_GAME_XBOX_INCOMPLETE.
        /// </summary>
        LC_SAVE_GAME_XBOX_INCOMPLETE,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_INSPECTOR_LOADING.
        /// </summary>
        LC_SAVE_INSPECTOR_LOADING,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION.
        /// </summary>
        LC_SAVE_LOCATION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_LBL_FMT | UserId | NumValidSaves.
        /// </summary>
        LC_SAVE_LOCATION_LBL_STEAM,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_LBL_FMT_XBOX | UserId | NumValidS....
        /// </summary>
        LC_SAVE_LOCATION_LBL_XBOX,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_MANUAL.
        /// </summary>
        LC_SAVE_LOCATION_MANUAL,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_STEAM_EMPTY.
        /// </summary>
        LC_SAVE_LOCATION_STEAM_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_XBOX_EMPTY.
        /// </summary>
        LC_SAVE_LOCATION_XBOX_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_XBOX_INSTALL_1.
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_1,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_XBOX_INSTALL_2.
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_2,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_LOCATION_XBOX_INSTALL_3.
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_3,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVE_WARNING.
        /// </summary>
        LC_SAVE_WARNING,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_CONTAINER_ID.
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_ID,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_CONTAINER_OWNER.
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_OWNER,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_CONTAINER_SLOTS_USED.
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_SLOTS_USED,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_CONTAINER_TYPE.
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_TYPE,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_DETECTED_PROPERTIES.
        /// </summary>
        LC_SAVEINSPECT_DETECTED_PROPERTIES,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_RAW_PROPERTIES.
        /// </summary>
        LC_SAVEINSPECT_RAW_PROPERTIES,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEINSPECT_SLOT_EMPTY.
        /// </summary>
        LC_SAVEINSPECT_SLOT_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVESEARCH_NUM_MATCHES | Label | NumMatches.
        /// </summary>
        LC_SAVESEARCH_CONTAINER_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVESEARCH_GRP_PAL_CONTAINERS.
        /// </summary>
        LC_SAVESEARCH_GRP_PAL_CONTAINERS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVESEARCH_GRP_SEARCH_SETTINGS.
        /// </summary>
        LC_SAVESEARCH_GRP_SEARCH_SETTINGS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVESEARCH_SETTINGS_MIN_IVS.
        /// </summary>
        LC_SAVESEARCH_SETTINGS_MIN_IVS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVESEARCH_SETTINGS_RESET.
        /// </summary>
        LC_SAVESEARCH_SETTINGS_RESET,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEWINDOW_TAB_DETAILS.
        /// </summary>
        LC_SAVEWINDOW_TAB_DETAILS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEWINDOW_TAB_SEARCH.
        /// </summary>
        LC_SAVEWINDOW_TAB_SEARCH,
        /// <summary>
        ///   Looks up a localized string similar to LC_SAVEWINDOW_TITLE | SaveLabel.
        /// </summary>
        LC_SAVEWINDOW_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_RUN.
        /// </summary>
        LC_SOLVER_RUN,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_ALLOWED_WILD_PALS.
        /// </summary>
        LC_SOLVER_SETTINGS_ALLOWED_WILD_PALS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS_DESC....
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS_DESCRIPTION.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_CPU.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_CPU,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_CPU_DESCRIPTION.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_CPU_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS_DES....
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_WILD_PALS.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_WILD_PALS,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_SETTINGS_MAX_WILD_PALS_DESCRIPTION.
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_WILD_PALS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_STATUS_BREEDING | StepNum | WorkSize.
        /// </summary>
        LC_SOLVER_STATUS_BREEDING,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOLVER_STATUS_FINISHED | Duration.
        /// </summary>
        LC_SOLVER_STATUS_FINISHED,
        /// <summary>
        ///   Looks up a localized string similar to LC_SOURCE_PALS.
        /// </summary>
        LC_SOURCE_PALS,
        /// <summary>
        ///   Looks up a localized string similar to LC_STARTUP_LOADING.
        /// </summary>
        LC_STARTUP_LOADING,
        /// <summary>
        ///   Looks up a localized string similar to LC_TARGET_PAL.
        /// </summary>
        LC_TARGET_PAL,
        /// <summary>
        ///   Looks up a localized string similar to LC_TARGET_PALS.
        /// </summary>
        LC_TARGET_PALS,
        /// <summary>
        ///   Looks up a localized string similar to LC_TRAITS_COUNT_EMPTY.
        /// </summary>
        LC_TRAITS_COUNT_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to LC_TRAITS_COUNT_RANDOM | NumRandom.
        /// </summary>
        LC_TRAITS_COUNT_RANDOM,
        /// <summary>
        ///   Looks up a localized string similar to LC_TRAITS_COUNT_UNRECOGNIZED | NumUnrecognized.
        /// </summary>
        LC_TRAITS_COUNT_UNRECOGNIZED,
        /// <summary>
        ///   Looks up a localized string similar to LC_UNKNOWN_GUILD.
        /// </summary>
        LC_UNKNOWN_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to LC_UNKNOWN_PLAYER.
        /// </summary>
        LC_UNKNOWN_PLAYER,
        /// <summary>
        ///   Looks up a localized string similar to LC_UPDATE_AVAILABLE.
        /// </summary>
        LC_UPDATE_AVAILABLE,
        /// <summary>
        ///   Looks up a localized string similar to LC_WINDOW_TITLE.
        /// </summary>
        LC_WINDOW_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to LV_SOLVER_STATUS_INITIALIZING.
        /// </summary>
        LV_SOLVER_STATUS_INITIALIZING,
    }

}

