
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace PalCalc.UI.Localization {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationCodesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationCodesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalCalc.UI.Localization.LocalizationCodes", typeof(LocalizationCodesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
    }

    /// <summary>
    /// Keys of all available strings in the applications resx-resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public enum LocalizationCodes
    {
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_ABOUT_APP,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_ADD_FAKE_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_ADD_NEW_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_ANY_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_ANY_PLAYER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_BASE_ASSIGNED_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to BaseName.
        /// </summary>
        LC_BASE_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_BREEDING_TIME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_BREEDING_TIME_DESC,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_ALL_ATTACK_SKILLS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_ATTACK_SKILLS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_CANCEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_ENABLED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_EQUIPPED_ATTACK_SKILLS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER_FEMALE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER_MALE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER_NONE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER_OPPOSITE_WILDCARD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_GENDER_WILDCARD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_ATTACK,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_ATTACK_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_DEFENSE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_DEFENSE_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_HP,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IV_HP_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_IVS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_LEVEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_LOCATION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_MAP_COORDS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_OWNER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_PAL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_PALDEX_NUM_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_COMMON_UNKNOWN,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CRASHLOG_FAILED,
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        LC_CUSTOM_CONTAINER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINER_ADD_NEW,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINER_NEW_FIELD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINER_NEW_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINER_RENAME_FIELD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINER_RENAME_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINERS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_CONTAINERS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_SAVE_GAME_NAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_CUSTOM_SAVE_GAME_NAME_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to PalName.
        /// </summary>
        LC_DELETE_PAL_TARGET_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_DELETE_PAL_TARGET_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to CrashlogPath.
        /// </summary>
        LC_ERROR_HARD_CRASH,
        /// <summary>
        ///   Looks up a localized string similar to CrashlogPath.
        /// </summary>
        LC_ERROR_SAVE_LOAD_FAILED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_CRASH_LOG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_CRASH_LOG_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_SAVE_CSV,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_SAVE_CSV_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_EXPORT_SAVE_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_GAME_SETTINGS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_GRAPH_ZOOM_CUSTOM,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_GRAPH_ZOOM_FILL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_GRAPH_ZOOM_PERCENT,
        /// <summary>
        ///   Looks up a localized string similar to GuildName.
        /// </summary>
        LC_GUILD_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INCLUDE_CUSTOM_PALS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INCLUDE_PALS_AT_BASE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INCLUDE_PALS_GPS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INCLUDE_PALS_IN_CAGES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INCLUDE_PALS_ON_EXPEDITIONS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_INSPECT_SAVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        /// <remarks>
        /// Label used to represent this language in the dropdown
        /// </remarks>
        LC_ITL_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_JOB_QUEUE_CLOSING_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_JOB_QUEUE_CLOSING_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        LC_JOB_QUEUE_HEADER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_LANG_CHANGED_RESTART,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_LANGUAGE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_LIST_SEPARATOR,
        /// <summary>
        ///   Looks up a localized string similar to X | Y.
        /// </summary>
        LC_LOC_COORD_BASE,
        /// <summary>
        ///   Looks up a localized string similar to Tab | X | Y.
        /// </summary>
        LC_LOC_COORD_DPS,
        /// <summary>
        ///   Looks up a localized string similar to Tab | X | Y.
        /// </summary>
        LC_LOC_COORD_GPS,
        /// <summary>
        ///   Looks up a localized string similar to Tab | X | Y.
        /// </summary>
        LC_LOC_COORD_PALBOX,
        /// <summary>
        ///   Looks up a localized string similar to SlotNum.
        /// </summary>
        LC_LOC_COORD_PARTY,
        /// <summary>
        ///   Looks up a localized string similar to X | Y.
        /// </summary>
        LC_LOC_COORD_VIEWING_CAGE,
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        LC_LOC_OWNED_BY,
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        LC_LOC_PALBOX_TAB,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MANUAL_SAVE_ALREADY_REGISTERED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MANUAL_SAVE_EXTENSION_LBL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MANUAL_SAVE_INCOMPLETE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MANUAL_SAVE_SELECTOR_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MEMORY_WARNING_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MEMORY_WARNING_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MULTIPLE_BREEDING_FARMS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_MULTIPLE_BREEDING_FARMS_DESC,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_NEW_TARGET_PAL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_NO_RESULTS_FAQ_1,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_NO_RESULTS_FAQ_2,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_NO_RESULTS_FAQ_3,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_NO_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_OPEN_IN_FILE_EXPLORER,
        /// <summary>
        ///   Looks up a localized string similar to TraitsList.
        /// </summary>
        LC_OPTIONAL_TRAITS_SUMMARY,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_CHECKLIST_SEARCH,
        /// <summary>
        ///   Looks up a localized string similar to PalName | PaldexNum.
        /// </summary>
        LC_PAL_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_ADD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_ADD_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_BUILTIN_NOT_OWNED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_BUILTIN_OWNED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_DELETE_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_PAL_LIST_PRESETS_DELETE_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_DELETE_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_NAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_OVERWRITE_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_PAL_LIST_PRESETS_OVERWRITE_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_OVERWRITE_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LIST_PRESETS_RENAME_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_PAL_LIST_PRESETS_RENAME_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_BASE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_CAPTURED,
        /// <summary>
        ///   Looks up a localized string similar to Count | LocType.
        /// </summary>
        LC_PAL_LOC_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_CUSTOM,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_DPS_FULL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_DPS_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_GPS_FULL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_GPS_SHORT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_PALBOX,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_PARTY,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_LOC_VIEWING_CAGE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_SRC_ANY_GUILD_MEMBER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_SRC_ANY_PLAYER_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_TARGET_OPTIONAL_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PAL_TARGET_REQUIRED_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to NumWild.
        /// </summary>
        LC_PAL_WILD_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_COST,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_NAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_SURGERY_ITEM,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_SURGERY_ITEM_NO,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_SURGERY_ITEM_YES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_PASSIVES_CHECKLIST_SURGERY_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to PlayerName.
        /// </summary>
        LC_PLAYER_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_POPUP_TITLE_LOADING_SAVE_FILE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RANDOM_TRAIT,
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        LC_REMOVE_CUSTOM_CONTAINER_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to SaveLabel.
        /// </summary>
        LC_REMOVE_SAVE_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_REMOVE_SAVE_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to TraitsList.
        /// </summary>
        LC_REQUIRED_TRAITS_SUMMARY,
        /// <summary>
        ///   Looks up a localized string similar to AvgAttempts.
        /// </summary>
        LC_RESULT_BREEDING_ATTEMPTS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_INPUT_LOCS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_IV_ATTACK,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_IV_AVERAGE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_IV_DEFENSE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_IV_HP,
        /// <summary>
        ///   Looks up a localized string similar to PalName | TraitsList | TimeEstimate.
        /// </summary>
        LC_RESULT_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to NumResults.
        /// </summary>
        LC_RESULT_LIST_TITLE_COUNT,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_LIST_TITLE_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_NUM_CAKES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_NUM_STEPS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_RESULT_TIME_ESTIMATE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_FILE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_FILE_RELOAD_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_FILE_RELOADING,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_GAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_GAME_ERROR,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_GAME_INVALID,
        /// <summary>
        ///   Looks up a localized string similar to PlayerName | PlayerLevel | DayNumber | WorldName.
        /// </summary>
        LC_SAVE_GAME_LBL,
        /// <summary>
        ///   Looks up a localized string similar to GameId.
        /// </summary>
        LC_SAVE_GAME_LBL_NO_METADATA,
        /// <summary>
        ///   Looks up a localized string similar to DayNumber | WorldName.
        /// </summary>
        LC_SAVE_GAME_LBL_SERVER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_GAME_REMOVE_BTN_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_GAME_XBOX_INCOMPLETE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_INSPECTOR_LOADING,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION,
        /// <summary>
        ///   Looks up a localized string similar to UserId | NumValidSaves.
        /// </summary>
        LC_SAVE_LOCATION_LBL_STEAM,
        /// <summary>
        ///   Looks up a localized string similar to UserId | NumValidSaves.
        /// </summary>
        LC_SAVE_LOCATION_LBL_XBOX,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_MANUAL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_STEAM_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_XBOX_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_1,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_2,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_LOCATION_XBOX_INSTALL_3,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVE_WARNING,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_ID,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_OWNER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_SLOTS_USED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_CONTAINER_TYPE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_DETECTED_PROPERTIES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_ON_EXPEDITION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_RAW_PROPERTIES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEINSPECT_SLOT_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to Label | NumMatches.
        /// </summary>
        LC_SAVESEARCH_CONTAINER_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVESEARCH_GRP_PAL_CONTAINERS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVESEARCH_GRP_SEARCH_SETTINGS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVESEARCH_SETTINGS_MAX_IVS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVESEARCH_SETTINGS_MIN_IVS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVESEARCH_SETTINGS_RESET,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEWINDOW_TAB_DETAILS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SAVEWINDOW_TAB_SEARCH,
        /// <summary>
        ///   Looks up a localized string similar to SaveLabel.
        /// </summary>
        LC_SAVEWINDOW_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SETTINGS_MASSIVE_EGG_INCUBATION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SETTINGS_MASSIVE_EGG_INCUBATION_DESC,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SETTINGS_PALBOX_TAB_SIZE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SETTINGS_PALBOX_TAB_SIZE_DESC,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SETTINGS_RESTART_REQUIRED_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_PAUSE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_RESUME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_RUN,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_ALLOWED_BRED_PALS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_ALLOWED_WILD_PALS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BRED_IRRELEVANT_TRAITS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_BREEDING_STEPS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_CPU,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_CPU_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_GOLD_COST,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_GOLD_COST_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_INPUT_IRRELEVANT_TRAITS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_SOLVER_STEPS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_SOLVER_STEPS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_WILD_PALS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_MAX_WILD_PALS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_SURGERY_ALLOWED_PASSIVES,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_USE_GENDER_REVERSERS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_SETTINGS_USE_GENDER_REVERSERS_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to StepNum | WorkSize.
        /// </summary>
        LC_SOLVER_STATUS_BREEDING,
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        LC_SOLVER_STATUS_FINISHED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOLVER_STATUS_INITIALIZING,
        /// <summary>
        ///   Looks up a localized string similar to NumProcessed | WorkSize.
        /// </summary>
        LC_SOLVER_STEP_STATUS_BREEDING,
        /// <summary>
        ///   Looks up a localized string similar to TotalSize.
        /// </summary>
        LC_SOLVER_STEP_STATUS_DONE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOURCE_PALS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOURCE_PALS_FILTERS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SOURCE_PALS_PLAYERS_AND_GUILDS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_STARTUP_LOADING,
        /// <summary>
        ///   Looks up a localized string similar to AddedPassive.
        /// </summary>
        LC_SURGERY_ADD_PASSIVE,
        /// <summary>
        ///   Looks up a localized string similar to NewGender.
        /// </summary>
        LC_SURGERY_CHANGE_GENDER,
        /// <summary>
        ///   Looks up a localized string similar to AddedPassive | RemovedPassive.
        /// </summary>
        LC_SURGERY_REPLACE_PASSIVE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_SURGERY_STEP_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TARGET_PAL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TARGET_PALS,
        /// <summary>
        ///   Looks up a localized string similar to InternalName.
        /// </summary>
        LC_TRAIT_LABEL_UNRECOGNIZED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_COUNT_EMPTY,
        /// <summary>
        ///   Looks up a localized string similar to NumRandom.
        /// </summary>
        LC_TRAITS_COUNT_RANDOM,
        /// <summary>
        ///   Looks up a localized string similar to NumUnrecognized.
        /// </summary>
        LC_TRAITS_COUNT_UNRECOGNIZED,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_ADD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_ADD_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_DELETE_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_TRAITS_PRESETS_DELETE_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_DELETE_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_NAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_OVERWRITE_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_TRAITS_PRESETS_OVERWRITE_MSG,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_OVERWRITE_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_PRESETS_RENAME_BTN_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to PresetName.
        /// </summary>
        LC_TRAITS_PRESETS_RENAME_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_SEARCH_DESCRIPTION,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_SEARCH_NAME,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_SEARCH_SEARCH,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_TRAITS_SEARCH_TITLE,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_UNKNOWN_GUILD,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_UNKNOWN_PLAYER,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_UPDATE_AVAILABLE,
        /// <summary>
        ///   Looks up a localized string similar to CageId.
        /// </summary>
        LC_VIEWING_CAGE_LABEL,
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        LC_WINDOW_TITLE,
    }

}

